#!/bin/sh

while read -r file
do
  case "$1" in
    "w") setbg "$file" ;;
    "d") [ "$(printf "no\\nyes" | rofi -dmenu -i -p "delete $file?")" = "yes" ] && rm -f "$file" && notify-send "$file deleted." ;; 
    "r") convert -rotate 90 "$file" "$file" ;;
    "R") convert -rotate -90 "$file" "$file" ;;
    "c") echo -n "$file" | xclip -selection clipboard && notify-send "$file name copied to clipboard.";;
    "u") upload "$file" ;; 
  esac 
done
